version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - VITE_REACT_APP_API_BASE_URL=http://localhost:8000
      - VITE_REACT_APP_API_KEY=${VITE_REACT_APP_API_KEY}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s